export const JOB_TITLES = [
  'Academic librarian',
  'Accountant',
  'Accounting technician',
  'Actuary',
  'Adult nurse',
  'Advertising account executive',
  'Advertising account planner',
  'Advertising copywriter',
  'Advice worker',
  'Advocate (Scotland)',
  'Aeronautical engineer',
  'Agricultural consultant',
  'Agricultural manager',
  'Aid worker/humanitarian worker',
  'Air traffic controller',
  'Airline cabin crew',
  'Amenity horticulturist',
  'Analytical chemist',
  'Animal nutritionist',
  'Animator',
  'Archaeologist',
  'Architect',
  'Architectural technologist',
  'Archivist',
  'Armed forces officer',
  'Aromatherapist',
  'Art therapist',
  'Arts administrator',
  'Auditor',
  'Automotive engineer',
  'Barrister',
  'Barrister’s clerk',
  'Bilingual secretary',
  'Biomedical engineer',
  'Biomedical scientist',
  'Biotechnologist',
  'Brand manager',
  'Broadcasting presenter',
  'Building control officer/surveyor',
  'Building services engineer',
  'Building surveyor',
  'Camera operator',
  'Careers adviser (higher education)',
  'Careers adviser',
  'Careers consultant',
  'Cartographer',
  'Catering manager',
  'Charities administrator',
  'Charities fundraiser',
  'Chemical (process) engineer',
  'Child psychotherapist',
  "Children's nurse",
  'Chiropractor',
  'Civil engineer',
  'Civil Service administrator',
  'Clinical biochemist',
  'Clinical cytogeneticist',
  'Clinical microbiologist',
  'Clinical molecular geneticist',
  'Clinical research associate',
  'Clinical scientist - tissue typing',
  'Clothing and textile technologist',
  'Colour technologist',
  'Commercial horticulturist',
  'Commercial/residential/rural surveyor',
  'Commissioning editor',
  'Commissioning engineer',
  'Commodity broker',
  'Communications engineer',
  'Community arts worker',
  'Community education officer',
  'Community worker',
  'Company secretary',
  'Computer sales support',
  'Computer scientist',
  'Conference organiser',
  'Consultant',
  'Consumer rights adviser',
  'Control and instrumentation engineer',
  'Corporate banker',
  'Corporate treasurer',
  'Counsellor',
  'Courier/tour guide',
  'Court reporter/verbatim reporter',
  'Credit analyst',
  'Crown Prosecution Service lawyer',
  'Crystallographer',
  'Curator',
  'Customs officer',
  'Cyber security specialist',
  'Dance movement therapist',
  'Data analyst',
  'Data scientist',
  'Data visualisation analyst',
  'Database administrator',
  'Debt/finance adviser',
  'Dental hygienist',
  'Dentist',
  'Design engineer',
  'Dietitian',
  'Diplomatic service',
  'Doctor (general practitioner, GP)',
  'Doctor (hospital)',
  'Dramatherapist',
  'Economist',
  'Editorial assistant',
  'Education administrator',
  'Electrical engineer',
  'Electronics engineer',
  'Employment advice worker',
  'Energy conservation officer',
  'Engineering geologist',
  'Environmental education officer',
  'Environmental health officer',
  'Environmental manager',
  'Environmental scientist',
  'Equal opportunities officer',
  'Equality and diversity officer',
  'Ergonomist',
  'Estate agent',
  'European Commission administrators',
  'Exhibition display designer',
  'Exhibition organiser',
  'Exploration geologist',
  'Facilities manager',
  'Field trials officer',
  'Financial manager',
  'Firefighter',
  'Fisheries officer',
  'Fitness centre manager',
  'Food scientist',
  'Food technologist',
  'Forensic scientist',
  'Geneticist',
  'Geographical information systems manager',
  'Geomatics/land surveyor',
  'Government lawyer',
  'Government research officer',
  'Graphic designer',
  'Health and safety adviser',
  'Health and safety inspector',
  'Health promotion specialist',
  'Health service manager',
  'Health visitor',
  'Herbalist',
  'Heritage manager',
  'Higher education administrator',
  'Higher education advice worker',
  'Homeless worker',
  'Horticultural consultant',
  'Hotel manager',
  'Housing adviser',
  'Human resources officer',
  'Hydrologist',
  'Illustrator',
  'Immigration officer',
  'Immunologist',
  'Industrial/product designer',
  'Information scientist',
  'Information systems manager',
  'Information technology/software trainers',
  'Insurance broker',
  'Insurance claims inspector',
  'Insurance risk surveyor',
  'Insurance underwriter',
  'Interpreter',
  'Investment analyst',
  'Investment banker - corporate finance',
  'Investment banker – operations',
  'Investment fund manager',
  'IT consultant',
  'IT support analyst',
  'Journalist',
  'Laboratory technician',
  'Land-based engineer',
  'Landscape architect',
  'Learning disability nurse',
  'Learning mentor',
  'Lecturer (adult education)',
  'Lecturer (further education)',
  'Lecturer (higher education)',
  'Legal executive',
  'Leisure centre manager',
  'Licensed conveyancer',
  'Local government administrator',
  'Local government lawyer',
  'Logistics/distribution manager',
  'Magazine features editor',
  'Magazine journalist',
  'Maintenance engineer',
  'Management accountant',
  'Manufacturing engineer',
  'Manufacturing machine operator',
  'Manufacturing toolmaker',
  'Marine scientist',
  'Market research analyst',
  'Market research executive',
  'Marketing account manager',
  'Marketing assistant',
  'Marketing executive',
  'Marketing manager (social media)',
  'Materials engineer',
  'Materials specialist',
  'Mechanical engineer',
  'Media analyst',
  'Media buyer',
  'Media planner',
  'Medical physicist',
  'Medical representative',
  'Mental health nurse',
  'Metallurgist',
  'Meteorologist',
  'Microbiologist',
  'Midwife',
  'Mining engineer',
  'Mobile developer',
  'Multimedia programmer',
  'Multimedia specialists',
  'Museum education officer',
  'Museum/gallery exhibition officer',
  'Music therapist',
  'Nanoscientist',
  'Nature conservation officer',
  'Naval architect',
  'Network administrator',
  'Nurse',
  'Nutritional therapist',
  'Nutritionist',
  'Occupational therapist',
  'Oceanographer',
  'Office manager',
  'Operational researcher',
  'Orthoptist',
  'Outdoor pursuits manager',
  'Packaging technologist',
  'Paediatric nurse',
  'Paramedic',
  'Patent attorney',
  'Patent examiner',
  'Pension scheme manager',
  'Personal assistant',
  'Petroleum engineer',
  'Pharmacist',
  'Pharmacologist',
  'Pharmacovigilance officer',
  'Photographer',
  'Physiotherapist',
  'Picture researcher',
  'Planning and development surveyor',
  'Planning technician',
  'Plant breeder',
  'Police officer',
  'Political party agent',
  'Political party research officer',
  'Practice nurse',
  'Press photographer',
  'Press sub-editor',
  'Prison officer',
  'Private music teacher',
  'Probation officer',
  'Product development scientist',
  'Production manager',
  'Programme researcher',
  'Project manager',
  'Psychologist (clinical)',
  'Psychologist (educational)',
  'Psychotherapist',
  'Public affairs consultant (lobbyist)',
  'Public affairs consultant (research)',
  'Public house manager',
  'Public librarian',
  'Public relations (PR) officer',
  'QA analyst',
  'Quality assurance manager',
  'Quantity surveyor',
  'Records manager',
  'Recruitment consultant',
  'Recycling officer',
  'Regulatory affairs officer',
  'Research chemist',
  'Research scientist',
  'Restaurant manager',
  'Retail banker',
  'Retail buyer',
  'Retail manager',
  'Retail merchandiser',
  'Retail pharmacist',
  'Sales executive',
  'Sales manager',
  'Scene of crime officer',
  'Secretary',
  'Seismic interpreter',
  'Site engineer',
  'Site manager',
  'Social researcher',
  'Social worker',
  'Software developer',
  'Soil scientist',
  'Solicitor',
  'Speech and language therapist',
  'Sports coach',
  'Sports development officer',
  'Sports therapist',
  'Statistician',
  'Stockbroker',
  'Structural engineer',
  'Systems analyst',
  'Systems developer',
  'Tax inspector',
  'Teacher (nursery/early years)',
  'Teacher (primary)',
  'Teacher (secondary)',
  'Teacher (special educational needs)',
  'Teaching/classroom assistant',
  'Technical author',
  'Technical sales engineer',
  'TEFL/TESL teacher',
  'Television production assistant',
  'Test automation developer',
  'Tour operator',
  'Tourism officer',
  'Tourist information manager',
  'Town and country planner',
  'Toxicologist',
  'Trade union research officer',
  'Trader',
  'Trading standards officer',
  'Training and development officer',
  'Translator',
  'Transportation planner',
  'Travel agent',
  'TV/film/theatre set designer',
  'UX designer',
  'Validation engineer',
  'Veterinary nurse',
  'Veterinary surgeon',
  'Video game designer',
  'Video game developer',
  'Volunteer work organiser',
  'Warehouse manager',
  'Waste disposal officer',
  'Water conservation officer',
  'Water engineer',
  'Web designer',
  'Web developer',
  'Welfare rights adviser',
  'Writer',
  'Youth worker',
]

export const COUNTRIES = [
  'United States',
  'Canada',
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and/or Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Croatia (Hrvatska)',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecudaor',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'France, Metropolitan',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard and Mc Donald Islands',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea, Democratic People's Republic of",
  'Korea, Republic of',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfork Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'St. Helena',
  'St. Pierre and Miquelon',
  'Sudan',
  'Suriname',
  'Svalbarn and Jan Mayen Islands',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States minor outlying islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City State',
  'Venezuela',
  'Vietnam',
  'Virigan Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Yugoslavia',
  'Zaire',
  'Zambia',
  'Zimbabwe',
]

export const DESCRIPTION = `Where does it come from?
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theor
y of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsu
m dolor sit amet..", comes from a line in section 1.10.32.
The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.`

export const RANDOM_POSTER_LINK =
  'https://api.lorem.space/image/movie?w=680&h=680'
