// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/layout/AdminHeader.vue')['default']
    BaseActionButton: typeof import('./components/utils/BaseActionButton.vue')['default']
    BaseImageInput: typeof import('./components/utils/BaseImageInput.vue')['default']
    BaseInput: typeof import('./components/utils/BaseInput.vue')['default']
    BaseRadioInputGroup: typeof import('./components/utils/BaseRadioInputGroup.vue')['default']
    BaseSearchAndSelectInput: typeof import('./components/utils/BaseSearchAndSelectInput.vue')['default']
    BaseSelectInput: typeof import('./components/utils/BaseSelectInput.vue')['default']
    BaseTextarea: typeof import('./components/utils/BaseTextarea.vue')['default']
    DarkModeToggle: typeof import('./components/utils/DarkModeToggle.vue')['default']
    DefaultHeader: typeof import('./components/layout/DefaultHeader.vue')['default']
    DefaultSidePanel: typeof import('./components/layout/DefaultSidePanel.vue')['default']
    IAkarIconsEye: typeof import('~icons/akar-icons/eye')['default']
    IAkarIconsEyeClosed: typeof import('~icons/akar-icons/eye-closed')['default']
    IBiSearch: typeof import('~icons/bi/search')['default']
    ICarbonAt: typeof import('~icons/carbon/at')['default']
    ICarbonClose: typeof import('~icons/carbon/close')['default']
    ICarbonLogout: typeof import('~icons/carbon/logout')['default']
    IEmojioneCrescentMoon: typeof import('~icons/emojione/crescent-moon')['default']
    IEmojioneDollarBanknote: typeof import('~icons/emojione/dollar-banknote')['default']
    IEmojioneMoneyBag: typeof import('~icons/emojione/money-bag')['default']
    IEosIconsLoading: typeof import('~icons/eos-icons/loading')['default']
    IEpBack: typeof import('~icons/ep/back')['default']
    IFlatColorIconsAddDatabase: typeof import('~icons/flat-color-icons/add-database')['default']
    IFlatColorIconsBearish: typeof import('~icons/flat-color-icons/bearish')['default']
    IFlatColorIconsCalendar: typeof import('~icons/flat-color-icons/calendar')['default']
    IFlatColorIconsCamera: typeof import('~icons/flat-color-icons/camera')['default']
    IFlatColorIconsCollaboration: typeof import('~icons/flat-color-icons/collaboration')['default']
    IFlatColorIconsGlobe: typeof import('~icons/flat-color-icons/globe')['default']
    IFlatColorIconsLink: typeof import('~icons/flat-color-icons/link')['default']
    IFlatColorIconsManager: typeof import('~icons/flat-color-icons/manager')['default']
    IFlatColorIconsMoneyTransfer: typeof import('~icons/flat-color-icons/money-transfer')['default']
    IIcOutlineNavigateNext: typeof import('~icons/ic/outline-navigate-next')['default']
    IMdiTriangleSmallUp: typeof import('~icons/mdi/triangle-small-up')['default']
    ITwemojiBookmarkTabs: typeof import('~icons/twemoji/bookmark-tabs')['default']
    ITwemojiOfficeWorker: typeof import('~icons/twemoji/office-worker')['default']
    ITwemojiSun: typeof import('~icons/twemoji/sun')['default']
    ITwemojiWorldMap: typeof import('~icons/twemoji/world-map')['default']
    OpportunityCard: typeof import('./components/utils/OpportunityCard.vue')['default']
    OpportunitySearch: typeof import('./components/utils/OpportunitySearch.vue')['default']
    PasswordInput: typeof import('./components/utils/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonOpportunityCard: typeof import('./components/utils/SkeletonOpportunityCard.vue')['default']
    TimeSlotInputGroup: typeof import('./components/page/dashboard/TimeSlotInputGroup.vue')['default']
  }
}

export {}
