// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/layout/AdminHeader.vue')['default']
    BaseActionButton: typeof import('./components/utils/BaseActionButton.vue')['default']
    BaseImageInput: typeof import('./components/utils/BaseImageInput.vue')['default']
    BaseInput: typeof import('./components/utils/BaseInput.vue')['default']
    BaseRadioInputGroup: typeof import('./components/utils/BaseRadioInputGroup.vue')['default']
    BaseSearchAndSelectInput: typeof import('./components/utils/BaseSearchAndSelectInput.vue')['default']
    BaseSelectInput: typeof import('./components/utils/BaseSelectInput.vue')['default']
    BaseTextarea: typeof import('./components/utils/BaseTextarea.vue')['default']
    CountryFilter: typeof import('./components/utils/CountryFilter.vue')['default']
    DarkModeToggle: typeof import('./components/utils/DarkModeToggle.vue')['default']
    DefaultHeader: typeof import('./components/layout/DefaultHeader.vue')['default']
    DefaultSidePanel: typeof import('./components/layout/DefaultSidePanel.vue')['default']
    OGTSidePanel: typeof import('./components/layout/OGTSidePanel.vue')['default']
    OGVSidePanel: typeof import('./components/layout/OGVSidePanel.vue')['default']
    OpportunityCard: typeof import('./components/utils/OpportunityCard.vue')['default']
    OpportunitySearch: typeof import('./components/utils/OpportunitySearch.vue')['default']
    PasswordInput: typeof import('./components/utils/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonOpportunityCard: typeof import('./components/utils/SkeletonOpportunityCard.vue')['default']
    TimeSlotInputGroup: typeof import('./components/page/dashboard/TimeSlotInputGroup.vue')['default']
  }
}

export {}
